name: what2see
description: A sample Polymer application
dependencies:
  core_elements: '>=0.3.0 <0.5.0'
  csvparser: '>=1.0.8 <2.0.0'
  jsonp: any
  paper_elements: '>=0.4.0 <0.5.0'
  polymer: '>=0.15.0 <1.0.0'
transformers:
- polymer:
    entry_points: web/what2see.html
